version: '3.8'

services:
  # Główna aplikacja Task Manager
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/taskmanager
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - task-manager-network

  # MongoDB - baza danych
  mongo:
    image: mongo:7.0-jammy
    container_name: task-manager-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=taskmanager
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - task-manager-network

  # Redis - cache
  redis:
    image: redis:7.2-alpine
    container_name: task-manager-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - task-manager-network

  # Nginx - reverse proxy (opcjonalny)
  nginx:
    image: nginx:1.25-alpine
    container_name: task-manager-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - task-manager-network

# Sieci
networks:
  task-manager-network:
    driver: bridge

# Wolumeny persistentne
volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local 